config/routes.rb
Rails.application.routes.draw do

  resources :posts
  resources :comments, only: [:create, :destroy]
  devise_for :users
  resources :users do
    resources :socs, only: [:create, :destroy]
    resources :egitims, only: [:create, :destroy]
    resources :yabancidils, only: [:create, :destroy]
    resources :deneyims, only: [:create, :destroy]
    resources :derneks, only: [:create, :destroy]
    resources :oduls, only: [:create, :destroy]
    resources :hobis, only: [:create, :destroy]
    resources :yeteneks, only: [:create, :destroy]
    resources :projelers,only: [:create, :destroy]
    member do
      get :friends
      get :followers
      get :deactivate
      get :mentionable
      get :kisisel
      get :projeler
      get :iletisim
      get :editsocialmedia
      get :egitimekle
      get :yabancidilekle
      get :deneyimekle
      get :dernekekle
      get :odulekle
      get :hobiekle
      get :yetenekekle
      get :projelerekle
      get :createcv

    end
  end

 

  resources :events do
    collection do
      get :calendar
    end
  end

  authenticated :user do
    root to: 'home#index', as: 'home'
  end
  unauthenticated :user do
    root 'home#portal'
  end

  match :follow, to: 'follows#create', as: :follow, via: :post
  match :unfollow, to: 'follows#destroy', as: :unfollow, via: :post
  match :like, to: 'likes#create', as: :like, via: :post
  match :unlike, to: 'likes#destroy', as: :unlike, via: :post
  match :find_friends, to: 'home#find_friends', as: :find_friends, via: :get
  match :about, to: 'home#about', as: :about, via: :get

  get 'home/portal'
  get 'home/front'
  get 'home/cv'
  get 'home/statistic'
  get 'home/sss'
  get 'home/hakkimizda'
 
 
  get 'ilan/list'
  get 'ilan/detay'
  

end

app/models/concerns/shared/callbacks.rb
# Copyright (c) 2015, @sudharti(Sudharsanan Muralidharan)
# Socify is an Open source Social network written in Ruby on Rails This file is licensed
# under GNU GPL v2 or later. See the LICENSE.

module Shared::Callbacks
  extend ActiveSupport::Concern

  included do
    before_destroy :remove_activity
    before_destroy :remove_likes
  end

  def remove_activity
    activity = PublicActivity::Activity.find_by(trackable_id: self.id, trackable_type: self.class.to_s, key: "#{self.class.to_s.downcase}.create")
    activity.destroy if activity.present?
    true
  end

  def remove_likes
    activity = PublicActivity::Activity.find_by(trackable_id: self.id, trackable_type: self.class.to_s, key: "#{self.class.to_s.downcase}.like")
    activity.destroy if activity.present?
  end

end

app/views/shared/_actions.html.erb
<% if user_signed_in? %>
  <div class="actions">
    <div class="row">
      <div class="col-xs-6 like">
        <%= render 'likes/form', likeable: resource %>
      </div>
      <div class="col-xs-6 comment">
        <%= link_to resource, class: 'btn btn-block' do %>
          <%= fa_icon 'comment' %> Yorumlar
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_activity.html.erb
<%= render_activity(activity) %>

app/views/shared/_avatar.html.erb
<% if user %>
  <%= link_to user_path(user) do %>
    <%= image_tag user.avatar.url || 'avatar.jpg', class: 'avatar' %>
  <% end %>
<% end %>

app/views/shared/_cover.html.erb
<% if user.cover.url %>
  <div class="cover" style="background-image: url(<%= user.cover.url %>);"></div>
<% else %>
  <div class="cover" style="background-image: url(/assets/cover.png);"></div>
<% end %>

app/views/shared/_created_at.html.erb
<div class="created-at">
  <%= fa_icon 'clock-o' %>
  <%= relative_time(activity.created_at)%> ago
</div>

app/views/shared/_footer.html.erb
<div class="container">
    <!----------- Footer ------------>
    <footer class="footer-bs">
        <div class="row">
        	<div class="col-md-4 footer-brand animated fadeInLeft">
            	<img src="https://resmim.net/f/CdsVLr.png" id="fimgs"></img>

                <p><br>© 2018 Fırat Üniversitesi <br>Teknoloji Fakültesi Yazılım Mühendisliği Mezun Bilgi Sistemi</p>
            </div>
        	<div class="col-md-4 footer-nav animated fadeInUp">
            	<h4>LINKLER —</h4>
            	<div class="col-md-8">
                    <ul class="list">
                        <li><a href="http://yeni.firat.edu.tr/content/akademik-takvim">Akademik Takvim</a></li>
                        <li><a href="https://obs.firat.edu.tr/">Öğrenci İşleri Otomasyonu</a></li>
                        <li><a href="https://indir.firat.edu.tr/">İndir Fırat</a></li>
                        <li><a href="http://kutuphane.db.firat.edu.tr/">Kütüphane Otomasyonu</a></li>
                        <li><a href="http://www.firatteknokent.com.tr/">Fırat Teknokent</a></li>
                    </ul>
                </div>
            	<div class="col-md-3">
                    <ul class="list">
                        <li><a href="#">Hakkımızda</a></li>
                        <li><a href="#">İletişim</a></li>
                        <li><a href="#">S.S.S</a></li>
                        <li><a href="#">Gizlilik</a></li>
                    </ul>
                </div>
            </div>
        	<div class="col-md-3 footer-ns animated fadeInRight">
            	<h4>Sosyal Medya</h4>
                <a href="https://facebook.com/firatedutr"><i id="social-fb" class="fa fa-facebook fa-3x social"></i></a>
	            <a href="https://twitter.com/firatedutr"><i id="social-tw" class="fa fa-twitter-square fa-3x social"></i></a>
	            <a href="https://google.com/firatedutr"><i id="social-gp" class="fa fa-google-plus-square fa-3x social"></i></a>
	            <a href="https://mail.firat.edu.tr/"><i id="social-em" class="fa fa-envelope-square fa-3x social"></i></a>
            </div>
        </div>
    </footer>
 
</div>

app/views/shared/_links.html.erb
<div id="user-info" class="well">
  <div class="text-center">
    <%= render 'shared/avatar', user: @user %><br>
    <h5><%= link_to @user.name, @user %></h5>
  </div>
  <h5>
    <%= fa_icon 'shield' %>
    <%= @user.posts_count %>Gönderi
  </h5>
  <% if @user.dob.present? %>
    <h5>
      <%= fa_icon @user.sex %>
      <%= age(@user.dob) %> Yaşında
    </h5>
  <% end %>
  <% if @user.location.present? %>
    <h5>
      <%= fa_icon 'map-marker' %>
      <%= @user.location %>
    </h5>
  <% end %>
  <h5>
    <i class="icon-record"></i> <%= @user.points %> Puan
  </h5>
  
  
  
  <br>
  <div class="text-center">
    <% unless is_current_user?(@user) %>
      <%= render 'follows/form', user: @user %>
      <h6><%= 'Follows you' if current_user.followed_by?(@user) %></h6>
    <% end %>
  </div>
</div>

app/views/shared/_movements.html.erb
<div id="movements" class="well">
<ul>
    <%= render_activities(@movements, layout: '/shared/activity') %> 
</ul>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-top">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <a class="navbar-brand" href="/"><img src="/assets/navbarlogo.png" width="150" height="45">
        </a>
    </div>
    
    <div class="collapse navbar-collapse" id="navbar-top">
      <ul class="nav navbar-nav navbar-right">
          <li><a href="<%= ilan_list_path %>">Kariyer</a></li>
        <% if user_signed_in? %>
          <li><a href="<%= user_path(current_user) %>">Sayfam</a></li>
          <li><a href="/home/portal">Portal</a></li>
          <li><a href="<%= home_front_path %>">Haberler</a></li>
    			<li><a href="<%= destroy_user_session_path %>" rel="nofollow" data-method="delete">Çıkış Yap</a></li>
        <% else %>
          <li><a href="/">Anasayfa</a></li>
          <li><%= link_to 'Haberler', home_front_path %></li>
          <li><%= link_to 'Üye Ol', new_user_registration_path %></li>
          <li><%= link_to 'Oturum Aç', user_session_path %></li>
        <% end %>
      </ul>
      
    </div>
    
  
  </div>
</nav>

app/views/shared/_no_resource.html.erb
<div class="no-resource text-center">
  
</div>

app/views/shared/_paginate.html.erb
<div id="endless-scroll" class="well text-center hidden">
  <%= image_tag 'ajax-loader.gif' %>
  <%= will_paginate resources %>
</div>

app/views/shared/_paginate.js.erb
<% if resources.next_page %>
  $(".pagination").replaceWith("<%= j will_paginate(resources) %>");
  $(".pagination").hide();
<% else %>
  $(window).off('scroll');
  $("#endless-scroll").remove();
<% end %>

app/views/shared/_user_info.html.erb
<div id="user-info" class="well">
		<div class="sidebar-nav">
        		<ul class="nav nav-list"> 
        		  <li class="active"><a href="/home/portal"><i class="icon-home"></i>Anasayfa </a></li>
        		  <li><a href="#"><i class="glyphicon glyphicon-list-alt"></i>Haber Kaynağı</a></li>
        		  <li><a href="<%= user_path(current_user) %>"><i class="icon-user"></i>Profil</a></li>
        		  <li><a href="<%= new_event_path %>"><i class="icon-calendar"></i>Etkinlik Takvimi</a></li>
        		  <li><a href="<%= find_friends_path%>" onclick="return nav.go(this, event, {noback: true, params: {_ref: 'left_nav'}});" class="left_row"><i class="glyphicon glyphicon-search"></i>Arkadaşlarını Bul</a></li>
        		  <li><a href="<%= friends_user_path(current_user) %>"><i class="glyphicon glyphicon-thumbs-up	"></i>Takip Ettiklerim</a></li>
        		  <li><a href="<%= followers_user_path(current_user) %>"><i class="glyphicon glyphicon-hand-right"></i>Takipçiler</a></li>
        		  <li><a href="<%= edit_user_path(current_user) %>"><i class="glyphicon glyphicon-edit"></i>Sayfanı Düzenle</a></li>
        		  <li><a href="<%= edit_user_registration_path %>"><i class="glyphicon glyphicon-compressed"></i>Parolanı Değiştir</a></li>
        		  <li><a href="<%= destroy_user_session_path %>" rel="nofollow" data-method="delete"><i class="glyphicon glyphicon-log-out"></i>Çıkış Yap</a></li>
        		</ul>
    </div> 
</div>    
    
    
    
    
    
    







    
    

app/views/shared/_wrapper.html.erb
<div class="search-area-wrapper">
     <div class="search-area container">
        <h3 class="search-header">Fırat Üniversitesi Teknoloji Fakültesi<br>Yazılım Mühendisliği Mezun Öğrenci Sistemi</h3>
        <p class="search-tag-line">Bilimin Parlayan Yıldızı...</p>
     </div>  
</div>